language: go
go:
- 1.4
script:
- go build .
- pwd && cd build && ./travis-build.sh
env:
  global:
    - GITHUB_REPO: 'missdeer/ifconfig'
    - secure: XA0FWLFpgx3eDBZTaQBVDIUrUp7SBoHdECSaH+WujZo9iOMd3pRHBZTx9yfw/YDSvkFlf8CjrSRB9fec/uXono7+w7JYwi23aPqcWK9uqJiBgg6CeWx7aChQNvb0cxEtSupiBPpYOC63O0tDJl4tR3IsjHXPTJyBZm9eTF6QVMw=
